import { mkdir, readFile, writeFile } from "node:fs/promises"
import { homedir } from "node:os"
import path from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"

const root = fileURLToPath(new URL("..", import.meta.url))
const configHome = process.env.XDG_CONFIG_HOME || path.join(homedir(), ".config")
const pluginDirectory = path.join(configHome, "opencode", "plugins", "opencode-productivity-plugin")
const marker = "// Generated by opencode-productivity-plugin npm run link.\n"

await mkdir(pluginDirectory, { recursive: true })
for (const [file, module] of [["index.ts", "server"], ["tui.ts", "tui"]]) {
  const target = path.join(pluginDirectory, file)
  const source = `${marker}export { default } from ${JSON.stringify(pathToFileURL(path.join(root, "dist", "src", `${module}.js`)).href)}\n`
  const current = await readFile(target, "utf8").catch((error) => {
    if (error.code === "ENOENT") return undefined
    throw error
  })
  if (current !== undefined && !current.startsWith(marker)) {
    throw new Error(`Refusing to overwrite an unmanaged plugin file: ${target}`)
  }
  if (current !== source) await writeFile(target, source)
}

console.log(`Linked OpenCode productivity plugin from ${root} at ${pluginDirectory}`)
